### ISSUE TITLE
Local storage is missing an ID Token, Please authenticate

### ISSUE THREAD

**Issue by LaTrita97** [furaiev/amazon-cognito-identity-dart-2#114]
Hi, I have this problem:

After the user authenticated ```_cognitoUser.authenticateUser(_authDetails)```, I call the logout function ```_cognitoUser.globalSignOut()```, and I receive this error: 
```Exception: Local storage is missing an ID Token, Please authenticate```

What I wrong? I receive this error also if I call ```_cognitoUser.signOut()```.

Seems that after I do the Login, the plugin does not refresh his tokens, I wrong?

If I reload the Application or I close the App and then I open it, the logout function ```_cognitoUser.globalSignOut()``` works well!

**Comment by neustaTerasa** [comment]
I have the same issue if I try to manually refresh the session by calling user.getSession().
Or is there another way to refresh the token?

**Comment by neustaTerasa** [comment]
I found a fix for my problem: The user pool was configured so that it is possible to login with email, but Cognito created a uuid as username. So the tokens where cached with the uuid as key. When I tried to restore the user from cache, I used the email, so that the lib could not find the cached token.
Now I store the username and use that to restore the token and it works. Don't know if it is the same problem for you, but maybe this can help.
