### ISSUE TITLE
AWS Cognito token valid even User pool is disabled or User is deleted 

### ISSUE THREAD

**Issue by bhanuka96** [furaiev/amazon-cognito-identity-dart-2#153]
I deleted my user from the user pool. But app side token is valid

```
  Future<bool> checkAuthenticated() async {
    if (_cognitoUser == null || _session == null) {
      return false;
    }

    return _session.isValid();
  }
```

I am using something like this logic on splash screen
```

if(checkAuthenticated() == true) {
 // navigate to dashboard
}else{
// navigate to sign in page
}
```

**Comment by furaiev** [comment]
Correct, it's because `isValid` is only a local expiration check.

https://github.com/furaiev/amazon-cognito-identity-dart-2/blob/ee254100344749e183fa9a517a477518e6807f6b/lib/src/cognito_user_session.dart#L58

I believe you should consider some API requests in order to check if the user still exists (if an authenticated user could be removed from the pool by your business logic).

**Comment by bhanuka96** [comment]
@furaiev Thanks. Is there any existing API in aws?
