### ISSUE TITLE
CognitoUser.sendMFACode throw CognitoClientException{statusCode: 400, code: InvalidParameterException, name: InvalidParameterException, message: Invalid device key given.}

### ISSUE THREAD

**Issue by huynguyenwork86** [furaiev/amazon-cognito-identity-dart-2#184]
import 'package:amazon_cognito_identity_dart_2/cognito.dart';

final userPool = CognitoUserPool(
  'ap-southeast-1_xxxxxxxxx',
  'xxxxxxxxxxxxxxxxxxxxxxxxxx',
);
final cognitoUser = CognitoUser('email@inspire.my', userPool);
final authDetails = AuthenticationDetails(
  username: 'email@inspire.my',
  password: 'Password001',
);
CognitoUserSession session;
try {
  session = await cognitoUser.authenticateUser(authDetails);
}on CognitoUserMfaRequiredException catch (e) {
  // handle SMS_MFA challenge
 //present a dialog to user to input the code from SMS message. When user presses done, call:
cognitoUser.sendMFACode("code");
} on CognitoClientException catch (e) {
  // handle Wrong Username and Password and Cognito Client
}catch (e) {
  print(e);
}

**Comment by CrisNegoianu** [comment]
Hey guys.

I'm also now getting this error when confirming the password of a new user.
Doesn't seem to happen any other time.

Can anyone else confirm this issue?

**Comment by moonshinephoenix** [comment]
I can confirm the original problem though it was with TOTP-MFA. I currently can't try out the SMS-MFA since i hit my monthly limit but it could be the same.

**Steps to reproduction**
Cognito pool setup
- Remember User Devices: always
- MFA: optional (propably required works as well)

Device setup
- You don't have a device key already stored in your CognitoStorage (if there is everything works ok)
-  MFA configured

1. Provide your credentials
2. Enter valid  MFA-Key
3. ->Error: Invalid device key
